dist: trusty
language: java
sudo: false
script: "./gradlew check integrationTest"

jdk:
  - oraclejdk8

services:
  - couchdb

before_install:
  - export TERM=dumb

cache:
  directories:
  - $HOME/.m2
